import {
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faCheck,
  // Saathratri change: extra icons for Cassandra search form UI (collapsible sections, validation, key display). Not in upstream.
  faCheckCircle,
  faChevronDown,
  faChevronRight,
  faCloud,
  faCogs,
  faDatabase,
  faEye,
  faFlag,
  faHeart,
  faHome,
  faKey,
  // End of Saathratri change.
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  // jhipster-needle-add-icon-import
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeIcons = [
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faCheck,
  // Saathratri change: extra icons for Cassandra search form UI (collapsible sections, validation, key display). Not in upstream.
  faCheckCircle,
  faChevronDown,
  faChevronRight,
  faCloud,
  faCogs,
  faDatabase,
  faEye,
  faFlag,
  faHeart,
  faHome,
  faKey,
  // End of Saathratri change.
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignOutAlt,
  faSignInAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  // jhipster-needle-add-icon-import
];
