package com.saathratri.developer.blog.domain;

import static com.saathratri.developer.blog.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SaathratriEntity2Asserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity2AllPropertiesEquals(SaathratriEntity2 expected, SaathratriEntity2 actual) {
        assertSaathratriEntity2AutoGeneratedPropertiesEquals(expected, actual);
        assertSaathratriEntity2AllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity2AllUpdatablePropertiesEquals(SaathratriEntity2 expected, SaathratriEntity2 actual) {
        assertSaathratriEntity2UpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity2AutoGeneratedPropertiesEquals(SaathratriEntity2 expected, SaathratriEntity2 actual) {
        assertThat(expected)
            .as("Verify SaathratriEntity2 auto generated properties")
            .satisfies(e ->
                assertThat(e.getCompositeId().getEntityTypeId())
                    .as("check entityTypeId")
                    .isEqualTo(actual.getCompositeId().getEntityTypeId())
            )
            .satisfies(e ->
                assertThat(e.getCompositeId().getYearOfDateAdded())
                    .as("check yearOfDateAdded")
                    .isEqualTo(actual.getCompositeId().getYearOfDateAdded())
            )
            .satisfies(e ->
                assertThat(e.getCompositeId().getArrivalDate()).as("check arrivalDate").isEqualTo(actual.getCompositeId().getArrivalDate())
            )
            .satisfies(e -> assertThat(e.getCompositeId().getBlogId()).as("check blogId").isEqualTo(actual.getCompositeId().getBlogId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity2UpdatableFieldsEquals(SaathratriEntity2 expected, SaathratriEntity2 actual) {
        assertThat(expected)
            .as("Verify SaathratriEntity2 relevant properties")
            .satisfies(e -> assertThat(e.getEntityName()).as("check entityName").isEqualTo(actual.getEntityName()))
            .satisfies(e -> assertThat(e.getEntityDescription()).as("check entityDescription").isEqualTo(actual.getEntityDescription()))
            .satisfies(e ->
                assertThat(e.getEntityCost()).as("check entityCost").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getEntityCost())
            )
            .satisfies(e -> assertThat(e.getDepartureDate()).as("check departureDate").isEqualTo(actual.getDepartureDate()));
    }
}
