package com.saathratri.developer.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SaathratriEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntityAllPropertiesEquals(SaathratriEntity expected, SaathratriEntity actual) {
        assertSaathratriEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertSaathratriEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntityAllUpdatablePropertiesEquals(SaathratriEntity expected, SaathratriEntity actual) {
        assertSaathratriEntityUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntityAutoGeneratedPropertiesEquals(SaathratriEntity expected, SaathratriEntity actual) {
        assertThat(expected)
            .as("Verify SaathratriEntity auto generated properties")
            .satisfies(e -> assertThat(e.getEntityId()).as("check entityId").isEqualTo(actual.getEntityId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntityUpdatableFieldsEquals(SaathratriEntity expected, SaathratriEntity actual) {
        assertThat(expected).as("Verify SaathratriEntity relevant properties");
    }
}
