# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDA0YTlhYzE5ZWFhNTZhZGQ3MGZjNjNhNDQwZjJiMTU1NmY1NjQxNGRkNDk0ZGY2N2FjODYyZGE5NWJlNWNkNTIyNWZhODZiMTBmYjcwNmY4ZGNlYTczNDMyZDlhZWEyYjExNzE0N2ZkMzczNzlmN2I1MWNmYzQwYWM0MzJiMDU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
