# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTFhNDA0NWNkNDVmNzQ1N2RiZmQ2NGQ3MDZhODllN2JlMzBmMjZmYWY5MWU0ZWMwM2E0NWNmZDg3MzEyNmEyYjliNzcwOGFiNWQwODUxYmY4NzlhZTlmODAzYWU3YWM2ODRlNDdlYzkyYjlhZmU2YTU4OGQyNDUyM2RkYThjNjM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
