#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDViMTMzOWM5NTg0ZGFhMmVkM2M1NWRmNjgyYWZmYjRlNzRiM2QwZmNkOTg2ZDIyZmI5ZTRmNDQ1MjY2Yzg0YmM5NThmNmI2YjdhMDYxMzY5YTYyMTY5YTMzYjMwN2U0ZWRkNg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
