#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZmQyM2ViZTY5Yjg3MTU2NDMzNjYxYzE1YjYyNTg4OWY4NTRlZGI1NjBkNzQ0Nzg0YTA0MDg4NjY3OTliM2Q3YmNhODZlZWVjNjg1ZjA2N2ZjYmIxOWY0YzhiMWVmYWNkYWY3MQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
