#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MzdjNzQ0MzFiM2VhMTUzZTI2ZDk5ODdjYzYxMzA5MzRhOTQwYTg3Zjg0ZjY2MzI0NmFiMmQ4YjI0ZjliMzVjZDVmMTY4NGU5NGYxZmVmNmE3NDcxNTNmM2JlMWM3M2VlOWJlYw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
