# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDBiMGY2NGNjMDc2NWQ0OWFhYzFjNjRiNjVjMWI2Y2IyZTlmMDJlNWNjM2ZjMTYzYTNiNThhYTdjMDQyODhlNDYzZmI3ZjZlMDQ4ZGRmOGQyZmZiOTM2NjRiMTcwZmMzNTUxZTc4Y2NhZTJlYjgzZWYwYzU0MDM3NmMzZWU5ODY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
