# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Y2M2YWViNDk0NDQwNTBlZjJmY2M1OTczOGRkMzUxM2NmOWMxMTFmMzg2ZGU5MTBhOTk1MjM2NmU4ODU2NTFjODE5NjU4YTdmZjNlMDQ3MDQyMTdjMzI1MjYyMGJhZTgxZDcwMDUzNGQzNjkzODM0NGM4NmYxYmY3MzJiMzg0MDg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
