# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmZjNjlkODczZmE4YWE0OGRjMGEzOGNjZWE1YjcwNzc5MDI0ZDM5ZDc2ZmUwYjk3NTU1MGY0NDBkOTNmYjAzYmYyNjg2ZTRlNGI3OGE4ZTc1YzQ5MTY3NzFkMmU4OGZiNDdkZDMwN2Y4MDllZjg4OTQyOGY2OTg0Njk1NDQzODc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
