# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGY2OTZiZWYxMGU4Zjc0YThkYzkzYzBjZTU5ZWNhZWY5OWIxYzdmODEzNTY2ZTkyN2FkYTkwY2I2NjQ4ZmM0YjQxMzVkMjk3MDJmYzU3YTM0MGY5MzMzMTFjYWMzZDExY2U5ZTk2MzQwMjc3YTE2YzExMmFjM2I4YzVmNGI5ZGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
