# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzAyMzNlNTVmZjk2MDBkMWM4NDE5NTE0ZjA2MzE5Y2IxYzNiMWQxY2E5NDNkNTBiNzc4N2UxZDEzNDFjNDI0ODYzNGZhYTg4NGJmNzczZDBhNzE0NWFlNTcwMGM0MTYwNjc4YzNjZWM0MjA2YzIxMjBkZjU3ZmMwNjdmNGYyMTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
