# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Mzc5NmQ1Y2QwNjk2ODY2MTM3NDZhNmMwNjFjZjdhOWQ4ZGYwNjE2NTFiYjczZjkwMjk2NjU1MGFhNzczZGEzNDQ5YmJlZjhkZjI1YjIwNDYzODhjZDM2NDgxNzAxOGExMDlmOGZjOTU4ZDc3ZWY4OGQ2Zjk2YjdmMzIzYzFlY2Y=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
