# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmNlYTA4NDE3YjcyMDVkZjAxZmNlM2I4M2ZlMWI3M2NhMjdmNGI3NmYyNjFhZGQzZmUxNTM4ZDRkZGFiZDhhNmY4NjQxNDg5ZTZmMTU0NDVkM2MyZDVhZTYwZmMwYWUxNmE5ZDA2NWYxOWI0ODM1NDI2Nzg1M2I1NzljYzI0Yjk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
