# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjE0M2MzMjZiYzQ1YmMxZjJhZDUyNTljM2U1NzRkNjU5YzNiZDJjMGZlMTA2YTQ3ZDA4NDcxODIxMmU3Mjc5YjVlMzk2NDg0Y2U5OWFmYWQyNjkyNmJmZjc2NGY1YTNiZDExMzhhNDJmMzU1NjA5MjY4ZjU1MmYzNjFkMWZiYjc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
