package com.saathratri.developer.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AddOnsAvailableByOrganizationAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAddOnsAvailableByOrganizationAllPropertiesEquals(
        AddOnsAvailableByOrganization expected,
        AddOnsAvailableByOrganization actual
    ) {
        assertAddOnsAvailableByOrganizationAutoGeneratedPropertiesEquals(expected, actual);
        assertAddOnsAvailableByOrganizationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAddOnsAvailableByOrganizationAllUpdatablePropertiesEquals(
        AddOnsAvailableByOrganization expected,
        AddOnsAvailableByOrganization actual
    ) {
        assertAddOnsAvailableByOrganizationUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAddOnsAvailableByOrganizationAutoGeneratedPropertiesEquals(
        AddOnsAvailableByOrganization expected,
        AddOnsAvailableByOrganization actual
    ) {
        assertThat(expected)
            .as("Verify AddOnsAvailableByOrganization auto generated properties")
            .satisfies(e ->
                assertThat(e.getCompositeId().getOrganizationId())
                    .as("check organizationId")
                    .isEqualTo(actual.getCompositeId().getOrganizationId())
            )
            .satisfies(e ->
                assertThat(e.getCompositeId().getEntityType()).as("check entityType").isEqualTo(actual.getCompositeId().getEntityType())
            )
            .satisfies(e ->
                assertThat(e.getCompositeId().getEntityId()).as("check entityId").isEqualTo(actual.getCompositeId().getEntityId())
            )
            .satisfies(e -> assertThat(e.getCompositeId().getAddOnId()).as("check addOnId").isEqualTo(actual.getCompositeId().getAddOnId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAddOnsAvailableByOrganizationUpdatableFieldsEquals(
        AddOnsAvailableByOrganization expected,
        AddOnsAvailableByOrganization actual
    ) {
        assertThat(expected)
            .as("Verify AddOnsAvailableByOrganization relevant properties")
            .satisfies(e -> assertThat(e.getAddOnType()).as("check addOnType").isEqualTo(actual.getAddOnType()))
            .satisfies(e -> assertThat(e.getAddOnDetailsText()).as("check addOnDetailsText").isEqualTo(actual.getAddOnDetailsText()))
            .satisfies(e ->
                assertThat(e.getAddOnDetailsDecimal())
                    .as("check addOnDetailsDecimal")
                    .containsExactlyEntriesOf(actual.getAddOnDetailsDecimal())
            )
            .satisfies(e ->
                assertThat(e.getAddOnDetailsBoolean()).as("check addOnDetailsBoolean").isEqualTo(actual.getAddOnDetailsBoolean())
            )
            .satisfies(e -> assertThat(e.getAddOnDetailsBigInt()).as("check addOnDetailsBigInt").isEqualTo(actual.getAddOnDetailsBigInt()));
    }
}
