package com.saathratri.developer.blog.domain;

import static com.saathratri.developer.blog.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SaathratriEntity2Asserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity2AllPropertiesEquals(SaathratriEntity2 expected, SaathratriEntity2 actual) {
        assertSaathratriEntity2AutoGeneratedPropertiesEquals(expected, actual);
        assertSaathratriEntity2AllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity2AllUpdatablePropertiesEquals(SaathratriEntity2 expected, SaathratriEntity2 actual) {
        assertSaathratriEntity2UpdatableFieldsEquals(expected, actual);
        assertSaathratriEntity2UpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity2AutoGeneratedPropertiesEquals(SaathratriEntity2 expected, SaathratriEntity2 actual) {
        assertThat(expected)
            .as("Verify SaathratriEntity2 auto generated properties")
            .satisfies(e -> assertThat(e.getEntityTypeId()).as("check entityTypeId").isEqualTo(actual.getEntityTypeId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity2UpdatableFieldsEquals(SaathratriEntity2 expected, SaathratriEntity2 actual) {
        assertThat(expected)
            .as("Verify SaathratriEntity2 relevant properties")
            .satisfies(e -> assertThat(e.getYearOfDateAdded()).as("check yearOfDateAdded").isEqualTo(actual.getYearOfDateAdded()))
            .satisfies(e -> assertThat(e.getArrivalDate()).as("check arrivalDate").isEqualTo(actual.getArrivalDate()))
            .satisfies(e -> assertThat(e.getBlogId()).as("check blogId").isEqualTo(actual.getBlogId()))
            .satisfies(e -> assertThat(e.getEntityName()).as("check entityName").isEqualTo(actual.getEntityName()))
            .satisfies(e -> assertThat(e.getEntityDescription()).as("check entityDescription").isEqualTo(actual.getEntityDescription()))
            .satisfies(e ->
                assertThat(e.getEntityCost()).as("check entityCost").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getEntityCost())
            )
            .satisfies(e -> assertThat(e.getDepartureDate()).as("check departureDate").isEqualTo(actual.getDepartureDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity2UpdatableRelationshipsEquals(SaathratriEntity2 expected, SaathratriEntity2 actual) {
        // empty method
    }
}
