package com.saathratri.developer.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SaathratriEntity4Asserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity4AllPropertiesEquals(SaathratriEntity4 expected, SaathratriEntity4 actual) {
        assertSaathratriEntity4AutoGeneratedPropertiesEquals(expected, actual);
        assertSaathratriEntity4AllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity4AllUpdatablePropertiesEquals(SaathratriEntity4 expected, SaathratriEntity4 actual) {
        assertSaathratriEntity4UpdatableFieldsEquals(expected, actual);
        assertSaathratriEntity4UpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity4AutoGeneratedPropertiesEquals(SaathratriEntity4 expected, SaathratriEntity4 actual) {
        assertThat(expected)
            .as("Verify SaathratriEntity4 auto generated properties")
            .satisfies(e -> assertThat(e.getOrganizationId()).as("check organizationId").isEqualTo(actual.getOrganizationId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity4UpdatableFieldsEquals(SaathratriEntity4 expected, SaathratriEntity4 actual) {
        assertThat(expected)
            .as("Verify SaathratriEntity4 relevant properties")
            .satisfies(e -> assertThat(e.getAttributeKey()).as("check attributeKey").isEqualTo(actual.getAttributeKey()))
            .satisfies(e -> assertThat(e.getAttributeValue()).as("check attributeValue").isEqualTo(actual.getAttributeValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaathratriEntity4UpdatableRelationshipsEquals(SaathratriEntity4 expected, SaathratriEntity4 actual) {
        // empty method
    }
}
