package com.saathratri.developer.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TajUserAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTajUserAllPropertiesEquals(TajUser expected, TajUser actual) {
        assertTajUserAutoGeneratedPropertiesEquals(expected, actual);
        assertTajUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTajUserAllUpdatablePropertiesEquals(TajUser expected, TajUser actual) {
        assertTajUserUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTajUserAutoGeneratedPropertiesEquals(TajUser expected, TajUser actual) {
        assertThat(expected)
            .as("Verify TajUser auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTajUserUpdatableFieldsEquals(TajUser expected, TajUser actual) {
        assertThat(expected).as("Verify TajUser relevant properties");
    }
}
