# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDk1NGM2ZjQ1MTM2NTNlZWIzYWE1NzRlOTU2NWZlZDFmM2UyNWM3ZjE1MmE4YTA5ZWM5ZDg2NmMwMDU0YmQzM2EzMmQ0ZDM2MDc5NzAzOGYwYjNlNTZlOWI0ZjI0N2RiMjJiYmMyZDVkMDhhNjcwY2YxZjJiNjdhYzdhN2ViMjM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
