# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjYxNTNhNDczMzQyOTE2NGQwMDM3ZmQ0NDJkNGZhNWM0ZDFmODliMzEyOWM3ODVhMTBmZDI2MWM4OWRlOGFlYTJkYTE0MWUxNDQwZTUxMzQ1YWIzOGNkNTQ2Mjk4NDRiZGY2YzJjMGQxNTg3NjBlYTU0ODEzN2FlYmYwMGU0MWY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
