# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NzlhZTlkN2YzZjBhZTliODVlZDZiNGExNmMzYjA4OGVkMGRmMTYzZjRlYWQ3MzZiNzc0MWNjNjA0OTc2ODU2MGNiMjJjNzc3MjgwNGY4OWQ0MmZjMDZhODExNjdiNmI4MjZiZTcyMzEyNjNjNmY5ZjNhMWI3OTdjZWFhNmM3ZTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
