# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Y2Y2NTRiZGIzMjBkZWZhZGExNDM0MzJmYTI1MWJiNDQ4ZjQ5MzI4ZTY2MWE1N2JmNzAwOGQwZTQyMDdkZGQ1OWFmYzQ1OWU4NTgzYTUyM2M0ZjU3ZWQ2ZjNkYTIwMzk3MjJjNWNhMDkwNTUwMzMxNzBmYjYxOGJkYmM1NjgwOWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
