# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDdjODc1M2YyMTUxMjI4YjRhMWNkMzM0NzE0ZjdhNDcyYjAzMDg2NmY2ZWQwMDg1OGZiMzkyMjY0YTdmNTUzMGVmYmJkZWE5YTQ0YjU3ZDBhYjZhMGJiODY4MWMwYzQ5N2M2MGIyYTgxOTRlODIzZDMxNThjNTQxNGFmNTM5ZDQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
