# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWJiMmQ0YThhNDlkNjRjMTE3NGEwMDU0ZGMzYmIwM2FlMTBjNGE5MDBiN2E4YzIyMGU3ZTA1ZWE5MzViZDI1MjQ4ZDJmMjk3NTNhZTAzNjljNDZmZDY0NjkxN2NhN2Y2MWEzZDFlN2I0MzU5ZjQxZDI5ZWNiZWZmZDdiZTU2ODY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
